version: "3.8"
x-default-service-common: &default-service-common
  restart: unless-stopped
  networks:
    - frontend

services:

  ipp-merchantadmin:
    <<: *default-service-common
    build: https://github.com/IPPWorldwide/MerchantPortal.git#main
    image: merchantadmin
    ports:
      - "9010:80"
    volumes:
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/virtual.conf:/etc/apache2/sites-enabled/demo.conf
    networks:
      frontend:
        aliases:
          - ipp-merchantadmin

  tests:
    <<: *default-service-common
    build: https://github.com/IPPWorldwide/PlatformsTest.git#main
    image: testcases
    depends_on:
      - ipp-merchantadmin
    environment:
      TEST_URL: http://ipp-merchantadmin/
    networks:
      frontend:
        aliases:
          - tests
    command: bash -c "
      sleep 25 &&
      cd /var/www/html/PlatformsTest-main &&
      ./vendor/bin/phpunit --verbose test
      "
networks:
  frontend:
    name: ipp-network
